### PR TITLE
Add tests for tree preview command

### PR DESCRIPTION
**Pull request by piohhmy**
As requested, this adds tests for #70 (along with a minor refactor).  Also, I think this closes issue #50?

### CODE REVIEW

**Comment by ddavison** [comment]
Thanks so much!  

Also, #50 is requesting that when you navigate using the arrow keys, (not pressing enter), that it previews files.  we should be able to add that later.

**Comment by ddavison** [comment]
added as a contributor as well

**Comment by piohhmy** [comment]
Great!  About #50, as I understand it, it is done, but maybe I'm missing something.  Currently you can navigate down the tree view with :arrow_up:  and :arrow_down:, then when you want to preview the file (without losing focus of tree view) you use :arrow_right:.  In the case of where you want to open the file for editing (losing focus of the tree view) then you press enter. That should cover it, yeah?

**Comment by ddavison** [comment]
actually, yea i think that sounds good.  I was thinking they wanted to be able to focus on a file in the tree, and it previews by default. (without pressing enter).

But i looked at sublime, and you actually press enter to preview files there.  I think we can close #50

**Comment by piohhmy** [comment]
Ahh you're right, I didn't realize the default keyboard nav in sublime previews every file on :arrow_up: and :arrow_down: when in the side bar.  I initially avoided that because I thought it would be too jarring visually, preferring instead an explicit :arrow_right: to preview.  Hm, since that is the behavior in Sublime it probably is better to match it exactly.

**Pull request merged**
